documentation:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'doc/**'
      - 'cloudinit/config/schemas/**'
  - base-branch: ['main']
packaging:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'debian/**'
  - base-branch: ['ubuntu/**']
