sudo: true
before_install:
    - test $TOXENV = py72 && DEPS="python-dev libyaml-dev" || true
    - test $TOXENV = py3 && DEPS="python3-dev libyaml-dev" || true
    - sudo apt-get update -q
    - test -n "$DEPS" && sudo apt-get update -q && \
      sudo apt-get install -y $DEPS || true
git:
    depth: 200
language: python
env:
    - TOXENV=py27
    - TOXENV=py3
    - TOXENV=flake8
    - TOXENV=tip-pycodestyle
    - TOXENV=tip-pyflakes
install: pip install tox
script:
    - tox
