sudo: false
before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y python3-dev python-dev libyaml-dev
git:
    depth: 200
language: python
env:
    - TOXENV=py27
    - TOXENV=py3
    - TOXENV=flake8
    - TOXENV=tip-pycodestyle
    - TOXENV=tip-pyflakes
install: pip install tox
script:
    - tox
