sudo: true
before_install:
    - sudo apt-get update -q
    - test $TOXENV = py72 && \
      sudo apt-get install -y python-dev libyaml-dev || true
    - test $TOXENV = py3 && \
      sudo apt-get install -y python3-dev libyaml-dev || true
git:
    depth: 200
language: python
env:
    - TOXENV=py27
    - TOXENV=py3
    - TOXENV=flake8
    - TOXENV=tip-pycodestyle
    - TOXENV=tip-pyflakes
install: pip install tox
script:
    - tox
