sudo: true
before_install:
    - test $TOXENV = 'py72' && DEPS="python-dev libyaml-dev"
    - test $TOXENV = 'py3' && DEPS="python3-dev libyaml-dev"
    - sudo apt-get update -q
    - sudo apt-get install -y $DEPS
git:
    depth: 200
language: python
env:
    - TOXENV=py27
    - TOXENV=py3
    - TOXENV=flake8
    - TOXENV=tip-pycodestyle
    - TOXENV=tip-pyflakes
install: pip install tox
script:
    - tox
