sudo: false
language: python
git:
    depth: 200
env:
  matrix:
    include:
      - TOXENV=py27
        addons:
          apt:
            packages:
             - python-dev
             - libyaml-dev
      - TOXENV=py3
        addons:
          apt:
            packages:
             - python-dev
             - libyaml-dev
      - TOXENV=flake8
      - TOXENV=tip-pycodestyle
      - TOXENV=tip-pyflakes
install: pip install tox
script:
    - tox -e $TOXENV
