#!/bin/bash
author=${1/\/cloud-init/}
if [ `grep -c ${author} tools/.lp-to-git-user` = 0 ]; then
    cat <<EOF
______________________________________________________________

Hello $author,

Thank you for your contribution to cloud-init.

In order to accept this pull request. Please confirm
that the Contributor License Agreement (CLA) has been signed
by following our hacking guide at:
https://cloudinit.readthedocs.io/en/latest/topics/hacking.html
______________________________________________________________
EOF
    exit 1
fi
cat <<EOF
______________________________________________________________

Hello $author,

Thank you for your continued contributions to cloud-init and
for signing the Contributor License Agreement for this project.

Once CI passes, team will assign a reviewer to your branch
to help get your branch merged.

Thanks again,
The cloud-init team
______________________________________________________________
EOF

exit 0
