#!/bin/sh
apt-get update
apt-get install \
    bash-completion \
    debhelper \
    git \
    iproute2 \
    meson \
    netplan.io \
    pkgconf \
    procps \
    python3-dev \
    python3-venv \
    shfmt \
    systemd-dev \
    tox
